dashboard/urls.py
from django.urls import path
from .views import dashboard_view, logout_view, login_view, pdb_test_view, person_view, create_person_view, \
    edit_person_view, delete_person_view, restore_person_view, add_country, add_region, add_district, add_locality
from .viewsets import ListCountryView, ListDistrictView, ListLocalityView, ListRegionView, ListBookNumberView, \
    ListHostelView, ListPasportystView, ListTypeLocalityView

# app_name = 'dashboard'

urlpatterns = [
    path('', dashboard_view, name="main"),
    # session

    # person
    path('person/create/', create_person_view, name="create_person"),
    path('person/<int:pk>/', person_view, name="show_person"),
    path('person/<int:pk>/edit/', edit_person_view, name="edit_person"),
    path('person/<int:pk>/delete/', delete_person_view, name="delete_person"),
    path('person/<int:pk>/restore/', restore_person_view, name="restore_person"),
    # auth
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    # add locality
    path('add-country/', add_country, name="add_country"),
    path('add-region/<int:country_id>', add_region, name="add_region"),
    path('add-district/<int:region_id>', add_district, name="add_district"),
    path('add-locality/', add_locality, name="add_locality"),
    # api
    path('country/', ListCountryView.as_view(), name="country_api"),
    path('region/', ListRegionView.as_view(), name="region_api"),
    path('district/', ListDistrictView.as_view(), name="district_api"),
    path('locality/', ListLocalityView.as_view(), name="locality_api"),
    path('pasportyst/', ListPasportystView.as_view(), name="pasportyst_api"),
    path('hostel/', ListHostelView.as_view(), name="hostel_api"),
    path('book-number/', ListBookNumberView.as_view(), name="book_api"),
    path('type-locality/', ListTypeLocalityView.as_view(), name="type_locality_api"),
    # testing
    path('populate-db/', pdb_test_view, ),

]

student_city/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('dashboard.urls')),
    path('admin/', admin.site.urls),
]

dashboard/models.py
from django.contrib.auth.models import User
from django.db import models


class Country(models.Model):
    name = models.CharField(max_length=256)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


class Region(models.Model):
    # область
    name = models.CharField(db_index=True, max_length=256)
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.name


    class Meta:
        ordering = ['name']


class District(models.Model):
    # район
    name = models.CharField(db_index=True, max_length=256)
    region = models.ForeignKey(Region, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


class TypeLocality(models.Model):
    name = models.CharField(max_length=32)
    short = models.CharField(max_length=8)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


class Locality(models.Model):
    name = models.CharField(db_index=True, max_length=256)
    type_locality = models.ForeignKey(TypeLocality, on_delete=models.SET_NULL, null=True)

    district = models.ForeignKey(District, on_delete=models.SET_NULL, blank=True, null=True)
    region = models.ForeignKey(Region, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.type_locality.short + ' ' + self.name

    class Meta:
        ordering = ['name']

    @property
    def full_locality(self):
        country_name = self.region.country.name
        region_name = self.region.name
        short_type_l = self.type_locality.short
        if self.district:
            district_name = ' ' + self.district.name + ','
        else:
            district_name = ''
        return f"{country_name}, {region_name},{district_name} {short_type_l} {self.name}"


class Hostel(models.Model):
    number = models.CharField(max_length=16)
    address = models.CharField(max_length=256)

    def __str__(self):
        return "№" + self.number


class Pasportyst(models.Model):
    name = models.CharField(max_length=256)
    active = models.BooleanField(default=True)
    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)

    def __str__(self):
        return self.name


class Book(models.Model):
    number = models.CharField(max_length=64)
    hostel = models.ForeignKey(Hostel, on_delete=models.SET_NULL, null=True)
    
    note = models.TextField()

    def __str__(self):
        return '(г. №' + self.hostel.number + ') ' + str(self.number)

    class Meta:
        ordering = ['hostel_id', 'number']


class PersonQuerySet(models.QuerySet):
    def active(self):
        return self.filter(deleted=False)

    def deleted(self):
        return self.filter(deleted=True)

    def any(self):
        return self


class PersonManager(models.Manager):
    def get_queryset(self):
        return PersonQuerySet(self.model, using=self._db)

    def editors(self):
        return

    def active(self):
        return self.get_queryset().active()

    def deleted(self):
        return self.get_queryset().deleted()

    def any(self):
        return self.get_queryset().any()


class Person(models.Model):

    name = models.CharField(db_index=True, max_length=128)
    surname = models.CharField(db_index=True, max_length=128,)
    patronymic = models.CharField(db_index=True, max_length=128, blank=True, default="")

    birthday = models.DateField(db_index=True)

    unique_number = models.CharField(max_length=256, blank=True, null=True)
    passport_number = models.CharField(max_length=32, blank=False, null=True)
    passport_authority = models.CharField(max_length=128, blank=False, null=True)
    date_of_issue = models.DateField(blank=False, null=True)

    registered = models.DateField(db_index=True, null=True)
    registered_period = models.DateField(db_index=True, null=True, blank=True)
    continued = models.DateField(db_index=True, null=True, blank=True)
    continued_period = models.DateField(db_index=True, null=True, blank=True)
    de_registered = models.DateField(db_index=True, null=True, blank=True)

    old_address = models.CharField(max_length=256, default='', null=True, blank=True)
    new_address = models.CharField(max_length=256, default='', null=True, blank=True)

    book = models.ForeignKey(Book, on_delete=models.SET_NULL, null=True)
    pasportyst = models.ForeignKey(Pasportyst, on_delete=models.SET_NULL, null=True)

    locality = models.ForeignKey(Locality, on_delete=models.SET_NULL, null=True)

    hostel = models.ForeignKey(Hostel, on_delete=models.SET_NULL, null=True)
    room = models.CharField(max_length=32, null=True, blank=True)

    created = models.DateField(auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, related_name="persons_created", default=None,
                                   null=True)
    updated = models.DateField(auto_now=True)
    updated_by = models.ForeignKey(User, on_delete=models.SET_NULL, related_name="persons_updated", default=None,
                                   null=True)

    deleted = models.BooleanField(default=False)
    deleted_time = models.DateTimeField(auto_now=True, blank=True)
    deleted_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    # sex = models.CharField(max_length=1, default="Ч")

    note = models.TextField(blank=True)

    people = PersonManager()
    objects = models.Manager()

    @property
    def book_number(self):
        if self.book:
            return self.book.number
        else:
            return None


    @property
    def short_name(self):
        p = ''
        if self.patronymic:
            p = ' ' + self.patronymic[0] + '. '
        return f"{self.surname} {self.name[0]}.{p}"

    @property
    def full_name(self):
        p = ''
        if self.patronymic:
            p = ' ' + self.patronymic + ' '
        return f"{self.surname} {self.name}{p}"

    def __str__(self):
        return self.name + ' ' + self.surname


class PersonHistory(models.Model):
    person_id = models.PositiveIntegerField(db_index=True)
    timestamp = models.DateTimeField(auto_now_add=True, blank=True)
    edited_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    data = models.TextField()


class DeletedPerson(models.Model):
    person_id = models.PositiveIntegerField(db_index=True)
    deleted_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, editable=False)
    timestamp = models.DateTimeField(auto_now_add=True, blank=True)

dashboard/forms.py
from django import forms
from .models import Person, Book, PersonHistory, Country, Region, Locality, District
from  .serializers import PersonTableSerializer


class CountryForm(forms.ModelForm):
    class Meta:
        model = Country
        fields = ['name']


class RegionForm(forms.ModelForm):
    class Meta:
        model = Region
        fields = ['name', 'country']


class DistrictForm(forms.ModelForm):
    class Meta:
        model = District
        fields = ['name', 'region']


class LocalityForm(forms.ModelForm):
    class Meta:
        model = Locality
        fields = ['name', 'type_locality', 'district', 'region']


class PersonForm(forms.ModelForm):

    class Meta:
        model = Person
        fields = ['surname', 'name', 'patronymic', 'birthday', 'unique_number', 'passport_number',
                  'passport_authority',
                  'date_of_issue', 'registered', 'registered_period', 'continued_period', 'continued', 'de_registered', 'new_address',
                  'pasportyst', 'old_address',
                  'locality', 'hostel', 'room', 'note', 'book']

    # def clean_name(self):
    #     data = self.cleaned_data['name']
    #     # if "fred@example.com" not in data:
    #     #     raise forms.ValidationError("You have forgotten about Fred!")
    #
    #     return data

    def save(self, commit=True):
        person = super(PersonForm, self).save(commit=False)
        # do custom stuff

        if commit:
            person.save()
        return person

dashboard/templates/add_country.html
{% extends 'index.html' %}


{% block title %}
    Додати країну | Студмістечко
{% endblock %}


{% block content %}
    <nav class="dashboard-nav">
        <div class="nav-wrapper">
            <ul class="left">
                <li><a id="close-or-back" href="javascript:"><i class="material-icons">arrow_back</i></a></li>
            </ul>
        </div>
    </nav>
    <div class="container">
        <div class="row">

            <div class="col s12">
                <div class="card-panel">
                    <p class="flow-text center">Додати країну</p>

                    <form method="POST" >
                        {% csrf_token %}

                        <div class="row">
                            <label for="id_name">Назва країни:</label>
                            <input type="text" name="name" maxlength="512"
                                   required id="id_name">
                        </div>

                        <div class="row">
                            <p class="center">
                                <button class="green btn waves-effect waves-light" type="submit">
                                    Зберегти
                                </button>
                            </p>
                        </div>

                    </form>

                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
    <script>
        $(document).ready(function () {

            function initPage() {
                listenNcapitalize('#id_name');
            }

            initPage();
        });
    </script>
{% endblock %}

dashboard/templates/person_create.html
{% extends 'index.html' %}


{% block title %}
    Додати запис | Студмістечко
{% endblock %}


{% block content %}
    <nav class="dashboard-nav">
        <div class="nav-wrapper">
            <ul class="left">
                <li><a id="close-or-back" href="javascript:"><i class="material-icons">arrow_back</i></a></li>
            </ul>
            <ul class="right">
                <li><a id="add-locality-nav-btn" target="_blank" href="javascript:">Додати наслений пункт<i
                                class="material-icons right">add</i></a></li>

                {% if user.is_authenticated %}
                    <li><a href="{% url "logout" %}">Вийти - {{ request.user.username }}</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <div class="container">
        <div class="row">

            <div class="col s12">
                <div class="card-panel">
                    <p class="flow-text center" style="margin-top: 0;">Додати запис</p>

                    {% include 'person_form.html' %}

                </div>
            </div>
        </div>
    </div>
{% endblock %}

 {% block script %}
     <script>
         $(document).ready(function () {

             function getBookNumbers() {
                 getValuesById('id_book_number');
             }

             function getHostels() {
                 getValuesById('id_hostel');
             }

             function getPasportysts() {
                 getValuesById('id_pasportyst');
             }

             function getCountries() {
                 getValuesById('id_country');
             }

             function getRegions(params = {}) {
                 getValuesById('id_region', params);
             }

             function getDistrict(params = {}) {
                 getValuesById('id_district', params);

                 $('#id_district').append('<option value="-1">Не застосовується</option>')
                 ;
             }

             function getLocality(params = {}) {
                 getValuesById('id_locality', params);
             }

             function getTypeLocalities() {
                 getValuesById('id_type_locality');
             }

             function getBooks(params = {}) {
                 getValuesById('id_book', params);
             }

             function listenForHostelChange() {
                 $("#id_hostel").change(function () {
                     getBooks({hostel_id: $(this).val()});
                 });
             }

             function listenForCountryChange() {
                 $("#id_country").change(function () {
                     getRegions({country_id: $(this).val()});
                 });
             }

             function listenForRegionChange() {
                 $("#id_region").change(function () {
                     getDistrict({region_id: $(this).val()});
                 });
             }

             function listenForDistrictChange() {
                 $("#id_district").change(function () {
                     if ($(this).val())
                         getLocality({district_id: $(this).val(), region_id: $('#id_region').val()});
                 });
             }

             function listenForTLChange() {
                 $("#id_type_locality").change(function () {
                     if ($(this).val())
                         getLocality({
                             district_id: $('#id_district').val(),
                             region_id: $('#id_region').val(),
                             type_locality_id: $(this).val()
                         });
                 });
             }

             function listenNcapitalize(field) {
                 $(field).on('keyup', function () {
                     $(this).capitalize();
                 }).capitalize();
             }

             function listenForIdCard() {

                 $('input[type=radio][name=id_passport]').change(function () {
                     $input = $('#id_unique_number');
                     if (this.value == '0') {
                         $input.removeAttr('disabled');
                         $($input.parent()).show();
                     } else if (this.value == '1') {
                         $input.attr('disabled', 'disabled');
                         $input.val('');
                         $($input.parent()).hide();
                     }
                 });
             }


             function listenForAddLocalityBTN() {
                 $("#add-locality-nav-btn").click(function () {
                     var new_window = PopupCenter("{% url 'add_locality' %}", 'Додати населений пункт', 'height=400, width=800');
                     var timer = setInterval(function () {
                         if (new_window.closed) {
                             if (confirm("Очистити поля для народження?"))
                                getCountries();

                             clearInterval(timer);
                         }
                     }, 1000);
                 });
             }


             function initPage() {

                 {% if person.locality is None %}
                     getCountries();
                     getTypeLocalities();
                 {% endif %}

                 listenForHostelChange();
                 listenForIdCard();
                 listenForCountryChange();
                 listenForRegionChange();
                 listenForDistrictChange();
                 listenForTLChange();

                 listenNcapitalize('#id_name');
                 listenNcapitalize('#id_surname');
                 listenNcapitalize('#id_patronymic');

                 listenFormSubmit('#person_form_id');

                 listenForAddLocalityBTN();


             }

             initPage();
         });
     </script>
 {% endblock %}

dashboard/templates/person_form.html
<form method="POST" id="person_form_id">
    {% csrf_token %}

    <!-- Surname | Name | Patronymic -->
    <div class="row no-margin-bottom">
        <div class="col s3">
            <label for="id_surname">Прізвище:</label>
            <input type="text" name="surname" maxlength="128"
                   required id="id_surname" value="{{ person.surname }}">
        </div>
        <div class="col s3">
            <label for="id_name">Ім'я:</label>
            <input type="text" name="name" maxlength="128" required
                   id="id_name" value="{{ person.name }}">
        </div>
        <div class="col s3">
            <label for="id_patronymic">Побатькові:</label>
            <input type="text" name="patronymic"
                   maxlength="128" id="id_patronymic" value="{{ person.patronymic }}">
        </div>
        <div class="col s3">
            <label for="id_birthday">Дата народження:</label>
            <input type="date" name="birthday" id="id_birthday" required
                   value="{% if person.birthday %}{{ person.birthday|date:"Y-m-d" }}{% endif %}"
                   min="1900-01-01" max="{% now "Y-m-d" %}">
        </div>
    </div>

    <!-- Birthday | unique number -->
    <div class="row">

        <div class="col s3">
            <div class="row no-margin-bottom" style="margin-top: 20px;">
                <div class="col s6">

                <label>
                    <input class="with-gap" name="id_passport" value="0" type="radio"
                           {% if not person or person.unique_number  %}checked{% endif %}/>
                    <span>ID-картка</span>
                </label>
                </div>

                <div class="col s4">
                    <label>
                        <input class="with-gap" name="id_passport" value="1" type="radio"
                               {% if person and not person.unique_number %}checked{% endif %}/>
                        <span>Паспорт</span>
                    </label>
                </div>
            </div>
        </div>
    </div>

    <!-- passport_number | passport_authority | date_of_issue -->
    <div class="row no-margin-bottom">
        <div class="col s2" {% if person and not person.unique_number %}style="display: none" {% endif %}>
            <label for="id_unique_number">Унікальний номер:</label>
            <input type="text" {% if person and not person.unique_number %}disabled{% endif %}
                   value="{% if person.unique_number %}{{ person.unique_number }}{% endif %}"
                   name="unique_number"
                   maxlength="100"
                   id="id_unique_number">
        </div>
        <div class="col s2">
            <label for="id_passport_number">Номер паспорта:</label>
            <input type="text"
                   value="{% if person.passport_number %}{{ person.passport_number }}{% endif %}"
                   name="passport_number"
                   maxlength="32" required
                   id="id_passport_number">
        </div>
        <div class="col s2">
            <label for="id_date_of_issue">Дата видачі:</label>
            <input type="date" name="date_of_issue" required id="id_date_of_issue"
                   value="{% if person.date_of_issue %}{{ person.date_of_issue|date:"Y-m-d"  }}{% endif %}"
                   min="1900-01-01" max="{% now "Y-m-d" %}">
        </div>
        <div class="col s6">
            <label for="id_passport_authority">Орган видачі паспорта:</label>
            <input type="text"
                   value="{% if person.passport_authority %}{{ person.passport_authority }}{% endif %}"
                   name="passport_authority"
                   maxlength="128"
                   required
                   id="id_passport_authority">
        </div>
    </div>
    <p class=""><b>Реєстрація:</b></p>
    <!-- Registered | Period -->
    <div class="row">
        <div class="col s3">
            <label for="id_registered">Дата реєстрації:</label>
            <input type="date"
                   value="{% if person.registered %}{{ person.registered|date:"Y-m-d" }}{% endif %}"
                   name="registered"
                   required
                   id="id_registered">
        </div>

        <div class="col s3">
            <label for="id_registered_period">Термін реєстрації:</label>
            <input type="date"
                   value="{% if person.registered_period %}{{ person.registered_period|date:"Y-m-d" }}{% endif %}"
                   name="registered_period"
                   id="id_registered_period">
        </div>

        <div class="col s3">
            <label for="id_continued">Дата продовження:</label>
            <input type="date"
                   value="{% if person.continued %}{{ person.continued|date:"Y-m-d" }}{% endif %}"
                   name="continued"
                   id="id_continued">
        </div>

        <div class="col s3">
            <label for="id_continued_period">Термін продовження:</label>
            <input type="date"
                   value="{% if person.continued_period %}{{ person.continued_period|date:"Y-m-d" }}{% endif %}"
                   name="continued_period"
                   id="id_continued_period">
        </div>

    </div>

    <div class="row">
        <div class="col s4">
            <label for="id_old_address">Звідки прибув:</label>
            <input type="text" name="old_address"
                   value="{% if person.old_address %}{{ person.old_address }}{% endif %}"
                   maxlength="256"
                   placeholder="(Місто, Р-н, Вул, будинок, квартира)"
                   id="id_old_address">
        </div>

        <div class="col s4">
            <label for="id_de_registered">Дата зняття з реєс.:</label>
            <input type="date"
                   value="{% if person.de_registered %}{{ person.de_registered|date:"Y-m-d" }}{% endif %}"
                   name="de_registered"
                   id="id_de_registered">
        </div>
        <div class="col s4">
            <label for="id_new_address">Куди зареєтрований:</label>
            <input type="text" name="new_address"
                   value="{% if person.new_address %}{{ person.new_address }}{% endif %}"
                   maxlength="256"
                   placeholder="(Місто, Р-н, Вул, будинок, квартира)"
                   id="id_new_address">
        </div>
    </div>



    <!-- Book | Pasportyst -->
    <div class="row no-margin-bottom">

        <div class="col s3">
            <label for="id_hostel">Гуртожиток:</label>
            <select class="browser-default"
                    name="hostel"
                    id="id_hostel" required
                    data-source="{% url 'hostel_api' %}"
                    data-valueKey="id"
                    data-displayKey="number">

                <option value="">---------</option>
                {% for hostel in hostels  %}
                    <option value="{{ hostel.id }}" {% if hostel.id == person.hostel.id %}selected{% endif %}>{{ hostel.number }}</option>
                {% endfor %}
            </select>

        </div>
        <div class="col s3">

            <label for="id_book">Книга:</label>
            <select class="browser-default"
                    name="book"
                    id="id_book" required
                    data-source="{% url 'book_api' %}"
                    data-valueKey="id"
                    data-displayKey="number">

                <option value="" selected>---------</option>
                {% for book in book_numbers  %}
                    <option value="{{ book.id }}" {% if book.id == person.book.id %}selected{% endif %}>{{ book.number }}</option>
                {% endfor %}
            </select>
        </div>

        <div class="col s3">
            <label for="id_room">Кімната:</label>
            <input type="text" name="room" maxlength="32"
                   value="{% if person.room is not None %}{{ person.room }}{% endif %}"
                   id="id_room">
        </div>


        <div class="col s3">
            <label for="id_pasportyst">Паспортист:</label>
            <select class="browser-default"
                    name="pasportyst" required
                    id="id_pasportyst"
                    data-source="{% url 'pasportyst_api' %}"
                    data-valueKey="id"
                    data-displayKey="name">
                <option value="" selected>---------</option>
                {% for p in pasportysts  %}
                    <option value="{{ p.id }}" {% if p.id == person.pasportyst.id %}selected{% endif %}>{{ p.name }}</option>
                {% endfor %}
            </select>
        </div>
    </div>

    <p class=""><b>Місце народження:</b></p>
    <!-- Locality -->
    <div class="row">
        <div class="col s2">
            <label for="id_country">Країна:</label>
            <select class="browser-default"
                    name="country"
                    id="id_country"
                    data-source="{% url 'country_api' %}"
                    data-valueKey="id"
                    data-displayKey="name"
                    required>
                <option value="" selected>---------</option>
                {% for country in countries  %}
                    <option value="{{ country.id }}" {% if country.id == person.locality.region.country_id %}selected{% endif %}>{{ country.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="col s2">
            <label for="id_region">Область:</label>
            <select class="browser-default"
                    name="region"
                    id="id_region"
                    data-source="{% url 'region_api' %}"
                    data-valueKey="id"
                    data-displayKey="name">
                <option value="">---------</option>
                {% for region in regions  %}
                    <option value="{{ region.id }}" {% if region.id == person.locality.region_id %}selected{% endif %}>{{ region.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="col s3">
            <label for="id_district">Район:</label>
            <select class="browser-default"
                    name="district"
                    id="id_district"
                    data-source="{% url 'district_api' %}"
                    data-valueKey="id"
                    data-displayKey="name"
                    required>
                <option value="">---------</option>
                {% if person.locality and person.locality.district is None %}
                    <option value="-1" selected>Не застосовується</option>
                {% else %}
                    <option value="-1" >Не застосовується</option>
                {% endif %}
                {% for district in districts  %}
                    <option value="{{ district.id }}" {% if district.id == person.locality.district_id %}selected{% endif %}>{{ district.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="col s2">
            <label for="id_type_locality">Категорія н.п.:</label>
            <select class="browser-default"
                    name="type_locality"
                    id="id_type_locality"
                    data-source="{% url 'type_locality_api' %}"
                    data-valueKey="id"
                    data-displayKey="short"
                    required>
                <option value="" selected>---------</option>
                {% for tl in type_localities  %}
                    <option value="{{ tl.id }}" {% if tl.id == person.locality.type_locality_id %}selected{% endif %}>{{ tl.short }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="col s3">
            <label for="id_locality">Нас. пункт:</label>
            <select class="browser-default"
                    name="locality"
                    id="id_locality"
                    data-source="{% url 'locality_api' %}"
                    data-valueKey="id"
                    data-displayKey="name"
                    required>
                <option value="" selected>---------</option>
                {% for l in localities  %}
                    <option value="{{ l.id }}" {% if l.id == person.locality.id %}selected{% endif %}>{{ l.name }}</option>
                {% endfor %}
            </select>
        </div>
    </div>

    <!-- Hostel | Room -->
    <div class="row no-margin-bottom">

    </div>

    <p>
        <label for="id_note">Примітка:</label>
        <textarea name="note" cols="40" rows="10" id="id_note">{% if person.note %}{{ person.note }}{% endif %}</textarea>
    </p>
    <p class="center">
        <button class="green btn waves-effect waves-light" type="submit">
            Зберегти
        </button>
    </p>
</form>